[build]
base = "/"
command = "pnpm install --frozen-lockfile && pnpm run build --filter=@finra-ui/storybook"
publish = "apps/storybook/storybook-static"

[build.environment]
NODE_VERSION = "22"
NPM_FLAGS = "--version"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
