packages:
  - packages/*
  - apps/*

catalog:
  "@changesets/cli": 2.29.7
  "@commitlint/cli": 20.0.0
  "@commitlint/config-conventional": 20.0.0
  "@eslint/js": 9.36.0
  "@radix-ui/react-slot": 1.2.3
  "@storybook/addon-a11y": 8.6.14
  "@storybook/addon-essentials": 8.6.14
  "@storybook/addon-themes": 8.6.14
  "@storybook/blocks": 8.6.14
  "@storybook/react": 8.6.14
  "@storybook/react-vite": 8.6.14
  "@storybook/test": 8.6.14
  "@testing-library/jest-dom": 6.8.0
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/react": 18.3.3
  "@types/react-dom": 18.3.0
  "@vitejs/plugin-react": 5.0.4
  "@vitest/coverage-istanbul": 3.2.4
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  eslint: 9.36.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-jsx-a11y: 6.10.2
  "@types/eslint-plugin-jsx-a11y": 6.10.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  globals: 16.4.0
  husky: 9.1.7
  jsdom: 27.0.0
  lint-staged: 16.2.2
  prettier: 3.6.2
  react: 18.3.1
  react-dom: 18.3.1
  sass: 1.93.2
  storybook: 8.6.14
  turbo: 2.5.8
  typescript: 5.9.2
  typescript-eslint: 8.44.1
  vite: 6.3.6
  vite-plugin-dts: 4.5.1
  vitest: 3.2.4

hoist-pattern:
  - "@types/*"
  - eslint*
  - prettier*
  - typescript
  - vitest*
  - "@vitest/*"
  - "@testing-library/*"
  - vite*
  - sass

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

prefer-workspace-packages: true

public-hoist-pattern:
  - "*eslint*"
  - "*prettier*"
  - "*typescript*"
  - "*react*"
